[package]
name = "racing-wheel-telemetry-mudrunner"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false
description = "MudRunner / SnowRunner UDP bridge telemetry adapter"

[dependencies]
racing-wheel-telemetry-adapters = { path = "../telemetry-adapters" }
racing-wheel-telemetry-core = { path = "../telemetry-core" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
